logLevel: info
logDestinations: [stdout, file]
logFile: /userdata/rk-edge-ai/mediamtx-runtime.log
rtsp: yes
rtspAddress: :8555
rtmp: no
hls: no
srt: no
webrtc: yes
webrtcAddress: :8889
webrtcEncryption: no
webrtcAllowOrigin: '*'
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: :8189
webrtcIPsFromInterfaces: yes
webrtcAdditionalHosts: [127.0.0.1]
pathDefaults:
  sourceOnDemand: yes
  sourceOnDemandStartTimeout: 10s
  sourceOnDemandCloseAfter: 5s
paths:
  camera-1:
    source: rtsp://127.0.0.1:8554/focus/0
  camera-2:
    source: rtsp://127.0.0.1:8554/focus/1
  dual-view:
    source: rtsp://127.0.0.1:8554/mosaic
  demo-global:
    source: udp+mpegts://127.0.0.1:7000
  demo-roi:
    source: udp+mpegts://127.0.0.1:7001
