set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(RK_GCC_ROOT "$ENV{RK_GCC_ROOT}" CACHE PATH "Directory containing the AArch64 cross compiler")
if(NOT RK_GCC_ROOT OR NOT EXISTS "${RK_GCC_ROOT}/aarch64-none-linux-gnu-gcc")
  message(FATAL_ERROR "Set RK_GCC_ROOT to the AArch64 toolchain bin directory, or pass -DRK_GCC_ROOT=/path/to/toolchain/bin")
endif()
set(CMAKE_C_COMPILER "${RK_GCC_ROOT}/aarch64-none-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${RK_GCC_ROOT}/aarch64-none-linux-gnu-g++")
